### ISSUE TITLE
where is depends.bat,depends.sh,depends.jar?

### ISSUE THREAD

**Issue by flysunys** [multilang-depends/depends#1]
I cound not find them. Cound you explain that?

**Comment by flysunys** [comment]
I found it ! The version downloaded is missed

**Comment by gangz** [comment]
Currently it is contains in the release package.  The issue will keep open until we add the .sh and .bat file in source code, and put them in to release package automatically.

**Comment by gangz** [comment]
The v0.9.1 version put the depends.bat, depends.sh. It is also included in package files automatically.
