### ISSUE TITLE
Documentation of output file

### ISSUE THREAD

**Issue by juli1** [multilang-depends/depends#26]
Hello,

I do not see or find any documentation on the `json` file being produced.
I understand it contains the list of nodes in an array and then, the vertices between them in the `cells` values.
However, I do not understand the content.

More particularly, what are the possible `values` keys and values?

Is it documented somewhere? Where to find the list of the keys and their meaning?

Thanks!

```
{
    "src" : 10,
    "dest" : 12,
    "values" : {
      "ImplLink" : 4.0
    }
  }
```

**Comment by gangz** [comment]
Added two files under doc directory: ```dependency_types.md``` for supported dependency types, and ```output_format.md``` for the output format of json file.

**Comment by juli1** [comment]
Thanks!
