### ISSUE TITLE
UML file cannot be opened

### ISSUE THREAD

**Issue by gqhuang14920** [multilang-depends/depends#4]
UML file cannot be opened

**Comment by gangz** [comment]
would you please to paste the error message for investigation?

**Comment by gangz** [comment]
would you please paste the error message?  We already found a potential error and fixed it in newest commits (still not released yet).

**Comment by gangz** [comment]
uml file is for plantuml,  close comment due to no response from submitter. if any issue still exists, please re-open it . thanks
