### ISSUE TITLE
It seems that not all program can be drawn correctly

### ISSUE THREAD

**Issue by muafish** [multilang-depends/depends#9]
In my program,my '0' file depend on ' 1' file ,' 2'file  and' 4'file,but in the picture,' 0'file does not point to '1'file.
![QQ截图20190717152153](https://user-images.githubusercontent.com/52993792/61357080-35adcc80-a8aa-11e9-8246-e33eee3032f5.png)
![InkedQQ截图20190717152208_LI](https://user-images.githubusercontent.com/52993792/61357083-36def980-a8aa-11e9-9df8-ec7463153d5f.jpg)

**Comment by gangz** [comment]
"Include" is a very basic dependency relation. The issue looks more likely caused by improper configuration or usage.  Would you please give more details of how to re-produce the issue, better to post source codes and your command lines? Thanks.

**Comment by gangz** [comment]
No reply from the issue submitter for a long time. closed.
